// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrgzadeGv8wUwUdwasRCQJhqYjP2kOPI',
    appId: '1:416817352897:web:ea75da489657e892af0440',
    messagingSenderId: '416817352897',
    projectId: 'sicksensemobile',
    authDomain: 'sicksensemobile.firebaseapp.com',
    storageBucket: 'sicksensemobile.firebasestorage.app',
    measurementId: 'G-X9TZYX3NY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68aIoamr5MiSX8S3MOSD4rTgVlG11Ywk',
    appId: '1:416817352897:android:ee5c68b5db97a83eaf0440',
    messagingSenderId: '416817352897',
    projectId: 'sicksensemobile',
    storageBucket: 'sicksensemobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpaDs9g229OXiHhqYq1jSgtqrmm77Sys',
    appId: '1:416817352897:ios:d44965cbe5f888e2af0440',
    messagingSenderId: '416817352897',
    projectId: 'sicksensemobile',
    storageBucket: 'sicksensemobile.firebasestorage.app',
    iosBundleId: 'com.example.sickSenseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpaDs9g229OXiHhqYq1jSgtqrmm77Sys',
    appId: '1:416817352897:ios:d44965cbe5f888e2af0440',
    messagingSenderId: '416817352897',
    projectId: 'sicksensemobile',
    storageBucket: 'sicksensemobile.firebasestorage.app',
    iosBundleId: 'com.example.sickSenseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCrgzadeGv8wUwUdwasRCQJhqYjP2kOPI',
    appId: '1:416817352897:web:49c25137079fa08baf0440',
    messagingSenderId: '416817352897',
    projectId: 'sicksensemobile',
    authDomain: 'sicksensemobile.firebaseapp.com',
    storageBucket: 'sicksensemobile.firebasestorage.app',
    measurementId: 'G-DV4WTZL2Z4',
  );
}
